/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/interviewer.glb -t 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Confused RT'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    node_0: THREE.SkinnedMesh
    spine: THREE.Bone
    neutral_bone: THREE.Bone
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/interviewer.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group name="metarig" position={[0.005, 0, 0]}>
          <primitive object={nodes.spine} />
          <primitive object={nodes.neutral_bone} />
        </group>
        <skinnedMesh name="node_0" geometry={nodes.node_0.geometry} material={materials['Material.001']} skeleton={nodes.node_0.skeleton} position={[0.005, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/interviewer.glb')
