/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/interviewer_with_desk.glb -t -o src/components/InterviewerWithDesk.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube010_black_0: THREE.Mesh
    Cube011_key_0: THREE.Mesh
    Cube012_key002_0: THREE.Mesh
    Cube012_key_0: THREE.Mesh
    Cube012_key_0001: THREE.Mesh
    Cube012_key_0002: THREE.Mesh
    Cube012_Material026_0: THREE.Mesh
    Cube013_body_0: THREE.Mesh
    Cube013_body_0001: THREE.Mesh
    Cube013_body_0002: THREE.Mesh
    Cube013_body_0003: THREE.Mesh
    Cube013_body_0004: THREE.Mesh
    Cube013_body_0005: THREE.Mesh
    Cube013_body_0006: THREE.Mesh
    Cube013_body_0007: THREE.Mesh
    Cube013_body_0008: THREE.Mesh
    Cube013_body_0009: THREE.Mesh
    Cube013_body_0010: THREE.Mesh
    Cube013_body_0011: THREE.Mesh
    Cube013_body_0012: THREE.Mesh
    Cube013_body_0013: THREE.Mesh
    Cube013_body_0014: THREE.Mesh
    Cube013_body_0015: THREE.Mesh
    Cube013_body_0016: THREE.Mesh
    Cube013_body_0017: THREE.Mesh
    Cube013_body_0018: THREE.Mesh
    Cube014_black001_0: THREE.Mesh
    Cube014_black001_0001: THREE.Mesh
    Cube014_black001_0002: THREE.Mesh
    Cube014_black001_0003: THREE.Mesh
    Cube014_black001_0004: THREE.Mesh
    Cube014_black001_0005: THREE.Mesh
    Cube014_black001_0006: THREE.Mesh
    Cube014_black001_0007: THREE.Mesh
    Cube014_black001_0008: THREE.Mesh
    Cube014_black001_0009: THREE.Mesh
    Cube014_black001_0010: THREE.Mesh
    Cube014_black001_0011: THREE.Mesh
    Cube014_body_0: THREE.Mesh
    Cube014_body_0001: THREE.Mesh
    Cube014_body_0002: THREE.Mesh
    Cube014_body_0003: THREE.Mesh
    Cube014_body_0004: THREE.Mesh
    Cube014_body_0005: THREE.Mesh
    Cube014_body_0006: THREE.Mesh
    Cube014_body_0007: THREE.Mesh
    Cube014_body_0008: THREE.Mesh
    Cube015_body_0: THREE.Mesh
    Cube017_black_0: THREE.Mesh
    Cube018_black003_0: THREE.Mesh
    Cube019_black_0: THREE.Mesh
    Cube020_black_0: THREE.Mesh
    Cube021_body_0: THREE.Mesh
    Cube021_Dark_0: THREE.Mesh
    Cube021_Material028_0: THREE.Mesh
    Cube022_black003_0: THREE.Mesh
    Cube016_black002_0: THREE.Mesh
    Cube016_body_0: THREE.Mesh
    Cube016_dark_0: THREE.Mesh
    Cube016_glass002_0: THREE.Mesh
    Cube016_glass003_0: THREE.Mesh
    Cube016_Material024_0: THREE.Mesh
    Cube016_Material025_0: THREE.Mesh
    Cube016_screen_0: THREE.Mesh
    Text003_Material029_0: THREE.Mesh
    Object_77: THREE.Mesh
    node_0011: THREE.Mesh
    node_0012: THREE.Mesh
    node_0061: THREE.Mesh
    node_0062: THREE.Mesh
    node_0063: THREE.Mesh
    node_0064: THREE.Mesh
    node_0065: THREE.Mesh
    node_0066: THREE.Mesh
    node_0067: THREE.Mesh
    node_0068: THREE.Mesh
    node_0069: THREE.Mesh
    node_0070: THREE.Mesh
    node_0071: THREE.Mesh
    node_0072: THREE.Mesh
    node_0073: THREE.Mesh
    node_0074: THREE.Mesh
    node_0075: THREE.Mesh
    node_0076: THREE.Mesh
    node_0077: THREE.Mesh
    node_0078: THREE.Mesh
    node_0079: THREE.Mesh
    node_0080: THREE.Mesh
    node_0082: THREE.Mesh
    node_0083: THREE.Mesh
    node_0106: THREE.Mesh
    node_0109: THREE.Mesh
    node_0111: THREE.Mesh
    node_0007: THREE.Mesh
    node_0191: THREE.Mesh
    node_0017: THREE.Mesh
    node_01116: THREE.Mesh
    node_01116_1: THREE.Mesh
    node_0020: THREE.Mesh
    node_0339: THREE.Mesh
    node_0025: THREE.Mesh
    node_0026: THREE.Mesh
    node_0414: THREE.Mesh
    node_0030: THREE.Mesh
    node_0031: THREE.Mesh
    node_0559: THREE.Mesh
    node_0042: THREE.Mesh
    node_0588: THREE.Mesh
    node_0597: THREE.Mesh
    node_0598: THREE.Mesh
    node_0618: THREE.Mesh
    node_0622: THREE.Mesh
    node_0641: THREE.Mesh
    node_0659: THREE.Mesh
    node_0662: THREE.Mesh
  }
  materials: {
    black: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['key.002']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    body: THREE.MeshStandardMaterial
    ['black.001']: THREE.MeshStandardMaterial
    ['black.003']: THREE.MeshStandardMaterial
    Dark: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['black.002']: THREE.MeshStandardMaterial
    dark: THREE.MeshStandardMaterial
    ['glass.002']: THREE.MeshStandardMaterial
    ['glass.003']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.080']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function InterviewerWithDesk(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model/interviewer_with_desk.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[3.868, 4.027, 7.193]} rotation={[-1.542, 0.014, -2.265]} scale={5.672}>
        <group position={[-0.205, -0.08, -0.005]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[-0.392, 0.188, 0.018]} rotation={[0.001, 0, 0]} scale={[0.006, 0.001, 0.003]}>
              <mesh geometry={nodes.Cube010_black_0.geometry} material={materials.black} position={[0, 0.003, 0]} />
            </group>
            <group position={[0.005, 0.093, 0.027]} scale={0.259}>
              <mesh geometry={nodes.Cube012_key002_0.geometry} material={materials['key.002']} />
              <mesh geometry={nodes.Cube012_key_0.geometry} material={materials.material} />
              <mesh geometry={nodes.Cube012_key_0001.geometry} material={materials.material} />
              <mesh geometry={nodes.Cube012_key_0002.geometry} material={materials.material} />
              <mesh geometry={nodes.Cube012_Material026_0.geometry} material={materials['Material.026']} />
            </group>
            <group position={[-0.4, 0.213, 0.026]} scale={[0.001, 0.001, 0]}>
              <mesh geometry={nodes.Cube013_body_0.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0001.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0002.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0003.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0004.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0005.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0006.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0007.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0008.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0009.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0010.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0011.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0012.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0013.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0014.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0015.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0016.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0017.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
              <mesh geometry={nodes.Cube013_body_0018.geometry} material={materials.body} position={[-0.001, -0.001, 0]} />
            </group>
            <group position={[0.321, 0.213, 0.026]} scale={[0.001, 0.001, 0]}>
              <mesh geometry={nodes.Cube014_black001_0.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0001.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0002.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0003.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0004.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0005.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0006.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0007.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0008.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0009.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0010.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_black001_0011.geometry} material={materials['black.001']} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_body_0.geometry} material={materials.body} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_body_0001.geometry} material={materials.body} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_body_0002.geometry} material={materials.body} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_body_0003.geometry} material={materials.body} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_body_0004.geometry} material={materials.body} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_body_0005.geometry} material={materials.body} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_body_0006.geometry} material={materials.body} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_body_0007.geometry} material={materials.body} position={[-0.001, 0, 0]} />
              <mesh geometry={nodes.Cube014_body_0008.geometry} material={materials.body} position={[-0.001, 0, 0]} />
            </group>
            <group position={[-0.392, 0.227, 0.018]} rotation={[0.001, 0, 0]} scale={[0.006, 0.001, 0.003]}>
              <mesh geometry={nodes.Cube019_black_0.geometry} material={materials.black} position={[0, 0.001, 0]} />
            </group>
            <group position={[-0.392, 0.227, 0.02]} rotation={[0.001, 0, 0]} scale={[0.006, 0.001, 0.003]}>
              <mesh geometry={nodes.Cube020_black_0.geometry} material={materials.black} position={[0, 0.001, 0]} />
            </group>
            <group position={[0, 0.003, 0.017]} rotation={[-0.016, 0, 0]}>
              <mesh geometry={nodes.Cube021_body_0.geometry} material={materials.body} />
              <mesh geometry={nodes.Cube021_Dark_0.geometry} material={materials.Dark} />
              <mesh geometry={nodes.Cube021_Material028_0.geometry} material={materials['Material.028']} />
            </group>
            <group position={[0, 0.28, 0.027]} rotation={[-0.263, 0, 0]} scale={0.259}>
              <group position={[0.001, 0.015, -0.05]} rotation={[1.807, 0, 0]} scale={1.06}>
                <mesh geometry={nodes.Cube016_black002_0.geometry} material={materials['black.002']} />
                <mesh geometry={nodes.Cube016_body_0.geometry} material={materials.body} />
                <mesh geometry={nodes.Cube016_dark_0.geometry} material={materials.dark} />
                <mesh geometry={nodes.Cube016_glass002_0.geometry} material={materials['glass.002']} />
                <mesh geometry={nodes.Cube016_glass003_0.geometry} material={materials['glass.003']} />
                <mesh geometry={nodes.Cube016_Material024_0.geometry} material={materials['Material.024']} />
                <mesh geometry={nodes.Cube016_Material025_0.geometry} material={materials['Material.025']} />
                <mesh geometry={nodes.Cube016_screen_0.geometry} material={materials.screen} />
              </group>
              <mesh geometry={nodes.Text003_Material029_0.geometry} material={materials['Material.029']} position={[0.01, -0.011, 0.063]} rotation={[1.806, 0, 0]} scale={[0.044, 0.049, 0.045]} />
            </group>
            <mesh geometry={nodes.Cube011_key_0.geometry} material={materials.material} position={[0.14, 0.167, 0.027]} scale={0.259} />
            <mesh geometry={nodes.Cube015_body_0.geometry} material={materials.body} position={[0, -0.149, 0.025]} rotation={[0.001, 0, 0]} scale={0.121} />
            <mesh geometry={nodes.Cube017_black_0.geometry} material={materials.black} position={[-0.392, 0.188, 0.02]} rotation={[0.001, 0, 0]} scale={[0.006, 0.001, 0.003]} />
            <mesh geometry={nodes.Cube018_black003_0.geometry} material={materials['black.003']} position={[-0.393, 0.183, 0.019]} rotation={[0.001, 0, 0]} scale={[0.006, 0.008, 0.004]} />
            <mesh geometry={nodes.Cube022_black003_0.geometry} material={materials['black.003']} position={[-0.393, 0.222, 0.019]} rotation={[0.001, 0, 0]} scale={[0.006, 0.008, 0.004]} />
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Object_77.geometry} material={materials['Material.080']} position={[9.491, 0.911, -0.065]} />
      <mesh geometry={nodes.node_0011.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0012.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0061.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0062.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0063.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0064.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0065.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0066.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0067.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0068.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0069.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0070.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0071.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0072.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0073.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0074.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0075.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0076.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0077.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0078.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0079.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0080.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0082.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0083.geometry} material={materials['Material.002']} position={[0.509, -0.734, -12.023]} scale={21.203} />
      <mesh geometry={nodes.node_0106.geometry} material={materials['Material.002']} position={[8.569, 6.127, -0.482]} rotation={[0, 1.557, 0]} scale={[4.34, 4.085, 4.34]} />
      <mesh geometry={nodes.node_0109.geometry} material={materials['Material.002']} position={[3.769, 0.403, 2.702]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]} />
      <mesh geometry={nodes.node_0111.geometry} material={materials['Material.002']} position={[8.569, 6.127, -2.088]} rotation={[0, 1.557, 0]} scale={[4.34, 4.085, 4.34]} />
      <mesh geometry={nodes.node_0007.geometry} material={materials['Material.002']} position={[3.769, 0.403, 0.077]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]} />
      <mesh geometry={nodes.node_0191.geometry} material={materials['Material.002']} position={[8.178, 2.247, -3.107]} rotation={[0, 1.557, 0]} scale={[4.34, 4.085, 4.34]} />
      <mesh geometry={nodes.node_0017.geometry} material={materials['Material.002']} position={[4.419, 2.324, -3.161]} scale={[4.619, 4.348, 4.619]} />
      <group position={[3.769, 0.403, 0.077]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]}>
        <mesh geometry={nodes.node_01116.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.node_01116_1.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.node_0020.geometry} material={materials['Material.002']} position={[2.542, -0.055, 3.721]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]} />
      <mesh geometry={nodes.node_0339.geometry} material={materials['Material.002']} position={[2.747, -0.479, 3.131]} rotation={[0, 1.557, 0]} scale={19.921} />
      <mesh geometry={nodes.node_0025.geometry} material={materials['Material.002']} position={[3.503, 0.403, -0.057]} rotation={[0, 1.557, 0]} scale={[2.86, 2.692, 2.86]} />
      <mesh geometry={nodes.node_0026.geometry} material={materials['Material.002']} position={[2.542, 0.407, 3.721]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]} />
      <mesh geometry={nodes.node_0414.geometry} material={materials['Material.002']} position={[3.769, 0.403, 0.077]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]} />
      <mesh geometry={nodes.node_0030.geometry} material={materials['Material.002']} position={[2.542, 0.407, 3.721]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]} />
      <mesh geometry={nodes.node_0031.geometry} material={materials['Material.002']} position={[3.769, 0.403, 0.077]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]} />
      <mesh geometry={nodes.node_0559.geometry} material={materials['Material.002']} position={[-2.357, -0.055, 4.77]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]} />
      <mesh geometry={nodes.node_0042.geometry} material={materials['Material.002']} position={[3.503, 0.403, -0.057]} rotation={[0, 1.557, 0]} scale={[2.86, 2.692, 2.86]} />
      <mesh geometry={nodes.node_0588.geometry} material={materials['Material.002']} position={[3.467, 1.689, -9.409]} />
      <mesh geometry={nodes.node_0597.geometry} material={materials['Material.002']} position={[3.769, 0.865, 0.077]} rotation={[0, 1.557, 0]} scale={[16.223, 15.271, 16.223]} />
      <mesh geometry={nodes.node_0598.geometry} material={materials['Material.002']} position={[4.419, 2.324, -5.786]} scale={[4.619, 4.348, 4.619]} />
      <mesh geometry={nodes.node_0618.geometry} material={materials['Material.002']} position={[-5.583, -3.666, -18.921]} rotation={[0, 1.557, 0]} scale={3.512} />
      <mesh geometry={nodes.node_0622.geometry} material={materials['Material.002']} position={[8.569, 6.127, -3.107]} rotation={[0, 1.557, 0]} scale={[4.34, 4.085, 4.34]} />
      <mesh geometry={nodes.node_0641.geometry} material={materials['Material.002']} position={[8.178, 2.247, -3.107]} rotation={[0, 1.557, 0]} scale={[4.34, 4.085, 4.34]} />
      <mesh geometry={nodes.node_0659.geometry} material={materials['Material.002']} position={[8.178, 2.247, -3.107]} rotation={[0, 1.557, 0]} scale={[4.34, 4.085, 4.34]} />
      <mesh geometry={nodes.node_0662.geometry} material={materials['Material.002']} position={[3.503, 0.865, -0.057]} rotation={[0, 1.557, 0]} scale={[2.86, 2.692, 2.86]} />
    </group>
  )
}

useGLTF.preload('/model/interviewer_with_desk.glb')
