/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/interviewer.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect, useMemo } from 'react'
import { useGraph, type ObjectMap } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import type { GLTF } from 'three-stdlib'

type ActionName = 'Confused RT'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = ObjectMap & {
  nodes: {
    node_0: THREE.SkinnedMesh
    spine: THREE.Bone
    neutral_bone: THREE.Bone
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

interface InterviewerProps extends React.ComponentPropsWithoutRef<'group'> {
  triggerAnimation?: boolean
}

export function Interviewer({ triggerAnimation, ...props }: InterviewerProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/model/interviewer.glb') as GLTF & { animations: GLTFAction[] }
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const actionName: ActionName = 'Confused RT'
    const action = actions[actionName]
    
    if (triggerAnimation && action) {
      action.reset().fadeIn(0.5).play()
      
      // We can also make it finish and return to idle if we had an idle
      // For now, let's keep it simple.
    } else if (!triggerAnimation && action) {
      action.fadeOut(0.5)
    }
  }, [triggerAnimation, actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group name="metarig" position={[0.005, 0, 0]}>
          <primitive object={nodes.spine} />
          <primitive object={nodes.neutral_bone} />
        </group>
        <skinnedMesh 
          name="node_0" 
          geometry={nodes.node_0.geometry} 
          material={materials['Material.001']} 
          skeleton={nodes.node_0.skeleton} 
          position={[0.005, 0, 0]} 
          castShadow
          receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/model/interviewer.glb')
