# Generated by Django 6.0.3 on 2026-03-21 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jd_text', models.TextField()),
                ('resume_text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('final_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('sequence_order', models.IntegerField()),
                ('type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('WHITEBOARD', 'Whiteboard')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered'), ('EVALUATED', 'Evaluated')], default='PENDING', max_length=20)),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('whiteboard_json_data', models.JSONField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interview')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
